name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-update-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Set Docker Image Tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and Push
        run: |
          docker build -t frozenwater1/my-spring-kafka:${TAG} .
          docker push frozenwater1/my-spring-kafka:${TAG}
          docker tag frozenwater1/my-spring-kafka:${TAG} frozenwater1/my-spring-kafka:latest
          docker push frozenwater1/my-spring-kafka:latest

      # ğŸ‘‡ manifest repo clone
      - name: Checkout manifest repo
        uses: actions/checkout@v3
        with:
          repository: frozen-water/spring-kafka-manifest
          path: manifest
          token: ${{ secrets.GITHUB_TOKEN }}   # ë˜ëŠ” PAT

      # ğŸ‘‡ values.yaml ìˆ˜ì •
      - name: Update image tag in values.yaml
        run: |
          sed -i.bak "s/tag: .*/tag: ${TAG}/" manifest/my-spring-kafka/values.yaml
          rm manifest/my-spring-kafka/values.yaml.bak
      # ğŸ‘‡ commit & push
      - name: Commit and push changes
        run: |
          cd manifest
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add my-spring-kafka/values.yaml
          git commit -m "Update image tag to ${TAG}"
          git push origin main